// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package root

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

type kindDef struct {
	Name  string
	Color string
}

var kindDefs = []kindDef{
	{Name: "context", Color: "#4a7fd4"},
	{Name: "capability", Color: "#3daa6e"},
	{Name: "concept", Color: "#d4a535"},
	{Name: "invariant", Color: "#e05c5c"},
	{Name: "scenario", Color: "#9a6dd4"},
	{Name: "specification", Color: "#3db8c8"},
	{Name: "verification", Color: "#7aad4a"},
	{Name: "adr", Color: "#c07840"},
	{Name: "task", Color: "#888888"},
}

func Layout() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>cap — system documentation explorer</title><link rel=\"stylesheet\" href=\"/static/vendor/vs/editor/editor.main.css\"><link rel=\"stylesheet\" href=\"/static/app.css\"><script src=\"/static/vendor/htmx.min.js\"></script><script src=\"/static/vendor/d3.v7.min.js\"></script><script src=\"/static/vendor/vs/loader.js\"></script></head><body><div id=\"app\"><div id=\"header\"><span id=\"app-name\">cap</span> <input type=\"search\" id=\"search\" name=\"q\" placeholder=\"Search…\" autocomplete=\"off\" hx-get=\"/tree\" hx-trigger=\"input changed delay:300ms\" hx-target=\"#tree-body\" hx-include=\"#search,#kind-state\"> <input type=\"hidden\" id=\"kind-state\" name=\"kinds\"><div id=\"chips\"></div><select id=\"theme-select\"><option value=\"cap\">Cap</option> <option value=\"dracula\">Dracula</option> <option value=\"one-dark\">One Dark</option> <option value=\"nord\">Nord</option> <option value=\"catppuccin\">Catppuccin</option> <option value=\"github-dark\">GitHub Dark</option></select></div><div id=\"main\"><div id=\"tree-panel\"><div id=\"tree-head\"><div class=\"th\">Entity</div><div class=\"th\">Kind</div><div class=\"th\">ID</div><div class=\"th\">Status</div></div><div id=\"tree-body\" hx-get=\"/tree\" hx-trigger=\"load, kindchange from:body\" hx-include=\"#kind-state,#search\" hx-swap=\"innerHTML\"></div></div><div id=\"graph-panel\"><svg id=\"graph-svg\"></svg><div id=\"graph-btns\"><button class=\"gbtn\" id=\"btn-fit\">Fit</button> <button class=\"gbtn\" id=\"btn-rst\">Reset</button></div></div><div id=\"detail-panel\"></div></div></div><script src=\"/static/app.js\"></script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
