name: release

on:
  push:
    tags:
      - "v*"

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22

      - name: Build Linux desktop app
        run: nix build ".#capui"

      - name: Upload Linux binary
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: capui-linux
          path: result/bin/capui

      - name: Build Windows desktop app
        run: nix build ".#capui-windows"

      - name: Upload Windows binary
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: capui-windows
          path: result/bin/capui.exe

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22

      - name: Build macOS desktop app
        run: nix build ".#capui"

      - name: Upload macOS binary
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: capui-macos
          path: result/bin/capui

  release:
    needs: [linux, macos]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: capui-linux
          path: artifacts/linux

      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: capui-windows
          path: artifacts/windows

      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: capui-macos
          path: artifacts/macos

      - name: Create release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          mv artifacts/linux/capui artifacts/capui-linux
          mv artifacts/windows/capui.exe artifacts/capui-windows.exe
          mv artifacts/macos/capui artifacts/capui-macos
          gh release create "${{ github.ref_name }}" \
            artifacts/capui-linux \
            artifacts/capui-windows.exe \
            artifacts/capui-macos \
            --repo "${{ github.repository }}" \
            --generate-notes
